apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: angular-frontend
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: angular-frontend
    spec:
      containers:
      - args:
        - yarn
        - run
        - start
        image: gcr.io/aprendizaje-automatico/angular-frontend
        imagePullPolicy: ""
        name: angular-frontend
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: angular-frontend-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: angular-frontend-claim0
        persistentVolumeClaim:
          claimName: angular-frontend-claim0
status: {}
